name: Workflow Demo

on: 
  push

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID

    - name: Echo linux commands
      run: |
        pwd
        df -h
        uname -a
        ifconfig
        ls /
        
  Test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: echo test
      run: echo 'Test'

  Deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: echo test
      run: |
        apt install cowsay
        cowsay "Hello Anil"
        echo 'Deploy'



